CREATE TABLE Usuario (
                         useruuid VARCHAR(36) PRIMARY KEY,
                         name VARCHAR (50),
                         mail VARCHAR (50),
                         password VARCHAR (50),
                         created DATE,
                         modified DATE,
                         lastlogin DATE,
                         isactive VARCHAR (1)
);

CREATE TABLE Telefono (
                          idtelefono INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT   BY   1) PRIMARY KEY,
                          useruuid VARCHAR(36) not null,
                          number VARCHAR (20),
                          citycode VARCHAR (10),
                          contrycode VARCHAR (10)
);

ALTER TABLE Telefono
    ADD FOREIGN KEY (useruuid) REFERENCES Usuario(useruuid);

INSERT INTO USUARIO
( "USERUUID", "NAME", "MAIL", "PASSWORD", "CREATED", "MODIFIED", "LASTLOGIN", "ISACTIVE" )
VALUES ( '1', 'Carlos', 'carlos@correo.com.pe', 'carlos', DATE '2024-01-05', null, null, '1');

INSERT INTO TELEFONO
( "USERUUID", "NUMBER", "CITYCODE", "CONTRYCODE" ) VALUES ( '1', '997655489', '22', '1');
INSERT INTO TELEFONO
( "USERUUID", "NUMBER", "CITYCODE", "CONTRYCODE" ) VALUES ( '1', '997845215', '23', '1');
